apiVersion: v1
kind: Service
metadata:
  name: cilium-ingress
  namespace: kube-system
  labels:
    external-dns.invertedorigin.com/enabled: "true"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ingress.home.arpa
    external-dns.alpha.kubernetes.io/ttl: "60"
