apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webrtc-diagnostics

resources:
  - namespace.yaml
  - external-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - network-policy.yaml

configMapGenerator:
  - name: webrtc-diagnostics-app
    files:
      - main.go=app/main.go
      - go.mod=app/go.mod
      - go.sum=app/go.sum
      - index.html=app/public/index.html
      - app.js=app/public/app.js
      - style.css=app/public/style.css
