{
 "title": "Cellular Status",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Cell ID",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pcid", "legendFormat": "Cell ID: {{cellid}} " }
   ]
  },
  {
   "title": "Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pcid", "legendFormat": "Cell ID: {{cellid}} " }
   ]
  },
  {
   "title": "Duplex Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pcid", "legendFormat": "Cell ID: {{cellid}} " }
   ]
  },
  {
   "title": "Connection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pcid", "legendFormat": "Cell ID: {{cellid}} " }
   ]
  },
  {
   "title": "Band",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "band", "legendFormat": "Cell ID: {{cellid}} " }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(nrdlbw -2)  * 10", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SINR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sinr", "legendFormat": "Cell ID: {{cellid}} " }
   ]
  },
  {
   "title": "RSRQ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rsrq", "legendFormat": "Cell ID: {{cellid}} " }
   ]
  },
  {
   "title": "ARFCN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "arfcn", "legendFormat": "Cell ID: {{cellid}} " }
   ]
  },
  {
   "title": "PCID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pcid", "legendFormat": "Cell ID: {{cellid}} " }
   ]
  },
  {
   "title": "TX Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "txpower", "legendFormat": "Cell ID: {{cellid}} " }
   ]
  },
  {
   "title": "Signal",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sinr - (-10)) / (25 - (-10))",
     "legendFormat": "Cell ID: {{cellid}} "
    }
   ]
  },
  {
   "title": "RSRP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rsrp", "legendFormat": "Cell ID: {{cellid}} " }
   ]
  },
  {
   "title": "Latest Cell Info Table",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    { "expr": "pcid", "legendFormat": "Cell ID: {{cellid}} " }
   ]
  }
 ]
}