{
 "title": "Power To Choose",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Lowest Price over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "min(powertochoose_external_kwh_500_price{})",
     "legendFormat": "500 kWh"
    },
    {
     "expr": "min(powertochoose_external_kwh_1000_price{})",
     "legendFormat": "1000 kWh"
    },
    {
     "expr": "min(powertochoose_external_kwh_2000_price{})",
     "legendFormat": "2000 kWh"
    }
   ]
  },
  {
   "title": "Lowest Price by Term",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg((powertochoose_external_kwh_500_price{term=\"3\"}+powertochoose_external_kwh_1000_price{term=\"3\"}+powertochoose_external_kwh_2000_price{term=\"3\"})/3)",
     "legendFormat": "3 Month Plans"
    },
    {
     "expr": "avg((powertochoose_external_kwh_500_price{term=\"6\"}+powertochoose_external_kwh_1000_price{term=\"6\"}+powertochoose_external_kwh_2000_price{term=\"6\"})/3)",
     "legendFormat": "6 Month Plans"
    },
    {
     "expr": "avg((powertochoose_external_kwh_500_price{term=\"12\"}+powertochoose_external_kwh_1000_price{term=\"12\"}+powertochoose_external_kwh_2000_price{term=\"12\"})/3)",
     "legendFormat": "12 Month Plans"
    },
    {
     "expr": "avg((powertochoose_external_kwh_500_price{term=\"18\"}+powertochoose_external_kwh_1000_price{term=\"18\"}+powertochoose_external_kwh_2000_price{term=\"18\"})/3)",
     "legendFormat": "18 Month Plans"
    },
    {
     "expr": "avg((powertochoose_external_kwh_500_price{term=\"24\"}+powertochoose_external_kwh_1000_price{term=\"24\"}+powertochoose_external_kwh_2000_price{term=\"24\"})/3)",
     "legendFormat": "24 Month Plans"
    },
    {
     "expr": "avg((powertochoose_external_kwh_500_price{term=\"36\"}+powertochoose_external_kwh_1000_price{term=\"36\"}+powertochoose_external_kwh_2000_price{term=\"36\"})/3)",
     "legendFormat": "36 Month Plans"
    }
   ]
  },
  {
   "title": "Providers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "min_over_time(powertochoose_external_kwh_500_price[1h])"
    },
    {
     "expr": "min_over_time(powertochoose_external_kwh_1000_price[1h])"
    },
    {
     "expr": "min_over_time(powertochoose_external_kwh_2000_price[1h])"
    }
   ]
  }
 ]
}