{
 "title": "Royal Caribbean",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Year", "query": { "query": "label_values(datelabel)" } },
   { "name": "Month", "query": { "query": "label_values(datelabel)" } },
   { "name": "Ship", "query": { "query": "label_values(ship)" } },
   { "name": "DeparturePort", "query": { "query": "label_values(departureport)" } },
   { "name": "CruiseDays", "query": { "query": "label_values(days)" } },
   { "name": "CabinClass", "query": { "query": "label_values(stateroomclass)" } }
  ]
 },
 "panels": [
  {
   "title": "Interior",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "royal_external_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=\"INTERIOR\"}",
     "legendFormat": "{{ship}} in {{stateroomclass}} from {{departureport}} on {{datelabel}} for {{days}} days"
    }
   ]
  },
  {
   "title": "Ocean View",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "royal_external_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=\"OUTSIDE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balcony",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "royal_external_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=\"BALCONY\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Suite",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "royal_external_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=\"DELUXE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Table View",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "royal_external_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=~\"$CabinClass\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graph",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "repeat": "Ship",
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "royal_external_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=~\"$CabinClass\"}",
     "legendFormat": "{{ship}} in {{stateroomclass}} from {{departureport}} on {{datelabel}} for {{days}} days"
    }
   ]
  }
 ]
}