{
 "title": "Royal Caribbean Detailed",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Year",
    "query": {
     "query": "label_values(royal_detail_price,datelabel)"
    }
   },
   {
    "name": "Month",
    "query": {
     "query": "label_values(royal_detail_price,datelabel)"
    }
   },
   {
    "name": "Ship",
    "query": {
     "query": "label_values(royal_detail_price,ship)"
    }
   },
   {
    "name": "DeparturePort",
    "query": {
     "query": "label_values(royal_detail_price,departureport)"
    }
   },
   {
    "name": "CruiseDays",
    "query": {
     "query": "label_values(royal_detail_price,days)"
    }
   },
   {
    "name": "CabinClass",
    "query": {
     "query": "label_values(royal_detail_price,stateroomclass)"
    }
   },
   {
    "name": "CabinDetailClass",
    "query": {
     "query": "label_values(stateroomdetailclass)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## NOTE: Prices shown here assume two people in a stateroom and include all taxes and fees. "
   }
  },
  { "title": "Cruise Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Interior",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "royal_detail_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=\"INTERIOR\"}",
     "legendFormat": "{{ship}} in {{stateroomclass}} from {{departureport}} on {{datelabel}} for {{days}} days"
    }
   ]
  },
  {
   "title": "Ocean View",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "royal_detail_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=\"OUTSIDE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balcony",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "royal_detail_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=\"BALCONY\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Suite",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "royal_detail_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=\"DELUXE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Table View",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "royal_detail_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=~\"$CabinClass\", stateroomdetailclass=~\"$CabinDetailClass\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Averages by Ship and Cabin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Average Price by Cabin Class",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg by (stateroomclass) (royal_detail_price{departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=~\"$CabinClass\", ship=~\"$Ship\", stateroomdetailclass=~\"$CabinDetailClass\"})",
     "legendFormat": "{{stateroomclass}}"
    }
   ]
  },
  {
   "title": "Average Price by Cabin Detailed Class",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg by (stateroomdetailclass) (royal_detail_price{ship=~\"$Ship\", departureport=~\"$DeparturePort\", days=~\"$CruiseDays\", datelabel=~\"$Year-$Month-.*\", stateroomclass=~\"$CabinClass\", stateroomdetailclass=~\"$CabinDetailClass\"})",
     "legendFormat": "{{stateroomdetailclass}}"
    }
   ]
  },
  { "title": "HTTP Request Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Request Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "royal_external_url_connect_time_ms",
     "legendFormat": "Connect Time {{ url }}"
    },
    { "expr": "royal_external_url_dns_ms", "legendFormat": "DNS Lookup {{ url }}" },
    {
     "expr": "royal_external_url_first_byte_ms",
     "legendFormat": "First Byte {{ url }}"
    },
    { "expr": "royal_external_url_response_ms", "legendFormat": "Connect Time {{ url }}" }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg_over_time(scrape_duration_seconds{job=\"royalcaribbean-prometheus-exporter-experimental\"}[5m])",
     "legendFormat": "allocated"
    }
   ]
  }
 ]
}