apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dhi-pull-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: dhi-pull-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: >-
          {"auths":{"dhi.io":{"username":{{ .username | toJson }},"password":{{ .token | toJson }},"auth":{{ printf "%s:%s" .username .token | b64enc | toJson }}}}}
  data:
    - secretKey: username
      remoteRef:
        key: DHI_USERNAME
        conversionStrategy: Default
        decodingStrategy: None
    - secretKey: token
      remoteRef:
        key: DHI_PULL_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
