apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ssl-argocd-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: "cloudflare-issuer"
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - argocd.invertedorigin.com
    secretName: argocd-tls-domain
  rules:
  - host: argocd.invertedorigin.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
