namespace: argocd

resources:
- infra-repo.yaml
- root-application.yaml
- ingress.yaml
- external-secret.yaml

components:
- ../../components/namespace
- ../../components/default-project-lockdown

helmCharts:
- name: argocd-chart
  repo: oci://dhi.io
  version: 10.10.2
  releaseName: argocd
  namespace: argocd
  includeCRDs: true
  valuesFile: values.yaml

patches:
- target:
    kind: Service
    name: argocd-application-controller-metrics
  patch: |-
    - op: replace
      path: /metadata/name
      value: argocd-metrics
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
  patch: |-
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: ServerSideApply=true
