apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chatgpt-desktop-secret
  namespace: chatgpt-desktop
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: CHATGPT_DESKTOP_PASSWORD
        metadataPolicy: None
      secretKey: password
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: chatgpt-desktop-secret

