apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hblink-secrets
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: HBLINK_MASTER_PASSPHRASE
        metadataPolicy: None
      secretKey: masterPassphrase
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: HBLINK_44NET_WIREGUARD_CONFIG
        metadataPolicy: None
      secretKey: wireguardConfig
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: HBLINK_PARROT_PASSPHRASE
        metadataPolicy: None
      secretKey: parrotPassphrase
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: hblink-secrets
    template:
      engineVersion: v2
      data:
        hblink.cfg: |-
          [GLOBAL]
          PATH: ./
          PING_TIME: 5
          MAX_MISSED: 3
          USE_ACL: True
          REG_ACL: PERMIT:ALL
          SUB_ACL: DENY:1
          TGID_TS1_ACL: PERMIT:1337
          TGID_TS2_ACL: PERMIT:1337,9999

          [REPORTS]
          REPORT: False
          REPORT_INTERVAL: 60
          REPORT_PORT: 4321
          REPORT_CLIENTS: 127.0.0.1

          [LOGGER]
          LOG_FILE: /dev/null
          LOG_HANDLERS: console-timed
          LOG_LEVEL: INFO
          LOG_NAME: HBlink

          [ALIASES]
          TRY_DOWNLOAD: True
          PATH: /hblink3/aliases/
          PEER_FILE: peer_ids.json
          SUBSCRIBER_FILE: subscriber_ids.json
          TGID_FILE: talkgroup_ids.json
          PEER_URL: https://www.radioid.net/static/rptrs.json
          SUBSCRIBER_URL: https://www.radioid.net/static/users.json
          STALE_DAYS: 7

          [MASTER-1]
          MODE: MASTER
          ENABLED: True
          REPEAT: True
          MAX_PEERS: 5
          EXPORT_AMBE: False
          IP:
          PORT: 62031
          PASSPHRASE: {{ .masterPassphrase }}
          GROUP_HANGTIME: 5
          USE_ACL: True
          REG_ACL: PERMIT:ALL
          SUB_ACL: DENY:1
          TGID_TS1_ACL: PERMIT:1337
          TGID_TS2_ACL: PERMIT:1337,9999

          [PARROT]
          MODE: PEER
          ENABLED: True
          LOOSE: False
          EXPORT_AMBE: False
          IP: 127.0.0.1
          PORT: 54098
          MASTER_IP: 127.0.0.1
          MASTER_PORT: 54100
          PASSPHRASE: {{ .parrotPassphrase }}
          CALLSIGN: ECHO
          RADIO_ID: 9999
          RX_FREQ: 000000000
          TX_FREQ: 000000000
          TX_POWER: 0
          COLORCODE: 1
          SLOTS: 2
          LATITUDE: 0
          LONGITUDE: 0
          HEIGHT: 0
          LOCATION: Internal
          DESCRIPTION: Local Parrot
          URL:
          SOFTWARE_ID: HBLink3 Playback
          PACKAGE_ID: HBLink3
          GROUP_HANGTIME: 5
          OPTIONS:
          USE_ACL: True
          SUB_ACL: DENY:1
          TGID_TS1_ACL: DENY:ALL
          TGID_TS2_ACL: PERMIT:9999

        playback.cfg: |-
          [GLOBAL]
          PATH: ./
          PING_TIME: 5
          MAX_MISSED: 3
          USE_ACL: True
          REG_ACL: PERMIT:9999
          SUB_ACL: DENY:1
          TGID_TS1_ACL: DENY:ALL
          TGID_TS2_ACL: PERMIT:9999

          [REPORTS]
          REPORT: False
          REPORT_INTERVAL: 60
          REPORT_PORT: 4323
          REPORT_CLIENTS: 127.0.0.1

          [LOGGER]
          LOG_FILE: /dev/null
          LOG_HANDLERS: console-timed
          LOG_LEVEL: INFO
          LOG_NAME: Parrot

          [ALIASES]
          TRY_DOWNLOAD: False
          PATH: /tmp/parrot-aliases/
          PEER_FILE: peer_ids.json
          SUBSCRIBER_FILE: subscriber_ids.json
          TGID_FILE: talkgroup_ids.json
          PEER_URL: https://www.radioid.net/static/rptrs.json
          SUBSCRIBER_URL: https://www.radioid.net/static/users.json
          STALE_DAYS: 7

          [PARROT]
          MODE: MASTER
          ENABLED: True
          REPEAT: True
          MAX_PEERS: 1
          EXPORT_AMBE: False
          IP: 127.0.0.1
          PORT: 54100
          PASSPHRASE: {{ .parrotPassphrase }}
          GROUP_HANGTIME: 5
          USE_ACL: True
          REG_ACL: PERMIT:9999
          SUB_ACL: DENY:1
          TGID_TS1_ACL: DENY:ALL
          TGID_TS2_ACL: PERMIT:9999
        wg0.conf: "{{ .wireguardConfig }}"
