apiVersion: v1
kind: Service
metadata:
  annotations:
    lbipam.cilium.io/ips: "10.0.1.8"
  labels:
    app.kubernetes.io/instance: hblink
    app.kubernetes.io/name: hblink
    app.kubernetes.io/service: hblink
  name: hblink
spec:
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges:
    - 10.0.1.0/24
  ports:
    - name: dmr
      nodePort: 0
      port: 62031
      protocol: UDP
      targetPort: dmr
  selector:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: hblink
    app.kubernetes.io/name: hblink
  type: LoadBalancer
