router bgp 64512
 bgp router-id 10.0.1.1
 neighbor TALOS peer-group
 neighbor TALOS remote-as 64513
 neighbor 10.0.1.223 peer-group TALOS
 neighbor 10.0.1.103 peer-group TALOS
 neighbor 10.0.1.201 peer-group TALOS
 !
 address-family ipv4 unicast
  neighbor TALOS activate
  neighbor TALOS route-map K8S_VIPS_IN in
  neighbor TALOS route-map NO_ROUTES_OUT out
  maximum-paths 3
 exit-address-family
exit
!
route-map K8S_VIPS_IN permit 10
 match ip address prefix-list K8S_VIPS
exit
!
route-map NO_ROUTES_OUT deny 10
exit
!
ip prefix-list K8S_VIPS seq 5 permit 10.246.0.0/26 ge 32 le 32
